pipeline {
  agent {
    docker { image 'node:16-alpine' }
  }
  stages {
    stage('Test01') {
      steps {
        sh 'node --version'
      }
      steps {
        echo "this is my first pipeline"
      }
    }
  }
}
